/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.Bookmarks = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Bookmarks model module.
   * @module model/Bookmarks
   * @version v0
   */

  /**
   * Constructs a new <code>Bookmarks</code>.
   * @alias module:model/Bookmarks
   * @class
   * @param contentnodeId {String} 
   * @param user {String} 
   */
  var exports = function(contentnodeId, user) {
    this.contentnodeId = contentnodeId;
    this.user = user;
  };

  /**
   * Constructs a <code>Bookmarks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bookmarks} obj Optional instance to populate.
   * @return {module:model/Bookmarks} The populated <code>Bookmarks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contentnode_id'))
        obj.contentnodeId = ApiClient.convertToType(data['contentnode_id'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} contentnodeId
   */
  exports.prototype.contentnodeId = undefined;

  /**
   * @member {String} user
   */
  exports.prototype.user = undefined;

  return exports;

}));
