/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.DeviceChannelMetadata = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DeviceChannelMetadata model module.
   * @module model/DeviceChannelMetadata
   * @version v0
   */

  /**
   * Constructs a new <code>DeviceChannelMetadata</code>.
   * @alias module:model/DeviceChannelMetadata
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param numCoachContents {Number} 
   */
  var exports = function(id, name, numCoachContents) {
    this.id = id;
    this.name = name;
    this.numCoachContents = numCoachContents;
  };

  /**
   * Constructs a <code>DeviceChannelMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceChannelMetadata} obj Optional instance to populate.
   * @return {module:model/DeviceChannelMetadata} The populated <code>DeviceChannelMetadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('author'))
        obj.author = ApiClient.convertToType(data['author'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('tagline'))
        obj.tagline = ApiClient.convertToType(data['tagline'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('last_updated'))
        obj.lastUpdated = ApiClient.convertToType(data['last_updated'], 'String');
      if (data.hasOwnProperty('lang_code'))
        obj.langCode = ApiClient.convertToType(data['lang_code'], 'String');
      if (data.hasOwnProperty('lang_name'))
        obj.langName = ApiClient.convertToType(data['lang_name'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('root'))
        obj.root = ApiClient.convertToType(data['root'], 'String');
      if (data.hasOwnProperty('thumbnail'))
        obj.thumbnail = ApiClient.convertToType(data['thumbnail'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'Number');
      if (data.hasOwnProperty('available'))
        obj.available = ApiClient.convertToType(data['available'], 'String');
      if (data.hasOwnProperty('num_coach_contents'))
        obj.numCoachContents = ApiClient.convertToType(data['num_coach_contents'], 'Number');
      if (data.hasOwnProperty('public'))
        obj._public = ApiClient.convertToType(data['public'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {String} author
   */
  exports.prototype.author = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} tagline
   */
  exports.prototype.tagline = undefined;

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} lastUpdated
   */
  exports.prototype.lastUpdated = undefined;

  /**
   * @member {String} langCode
   */
  exports.prototype.langCode = undefined;

  /**
   * @member {String} langName
   */
  exports.prototype.langName = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} root
   */
  exports.prototype.root = undefined;

  /**
   * @member {String} thumbnail
   */
  exports.prototype.thumbnail = undefined;

  /**
   * @member {Number} version
   */
  exports.prototype.version = undefined;

  /**
   * @member {String} available
   */
  exports.prototype.available = undefined;

  /**
   * @member {Number} numCoachContents
   */
  exports.prototype.numCoachContents = undefined;

  /**
   * @member {Boolean} _public
   */
  exports.prototype._public = undefined;

  return exports;

}));
