/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.DevicePermissions = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DevicePermissions model module.
   * @module model/DevicePermissions
   * @version v0
   */

  /**
   * Constructs a new <code>DevicePermissions</code>.
   * @alias module:model/DevicePermissions
   * @class
   * @param user {String} 
   */
  var exports = function(user) {
    this.user = user;
  };

  /**
   * Constructs a <code>DevicePermissions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DevicePermissions} obj Optional instance to populate.
   * @return {module:model/DevicePermissions} The populated <code>DevicePermissions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'String');
      if (data.hasOwnProperty('is_superuser'))
        obj.isSuperuser = ApiClient.convertToType(data['is_superuser'], 'Boolean');
      if (data.hasOwnProperty('can_manage_content'))
        obj.canManageContent = ApiClient.convertToType(data['can_manage_content'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {String} user
   */
  exports.prototype.user = undefined;

  /**
   * @member {Boolean} isSuperuser
   */
  exports.prototype.isSuperuser = undefined;

  /**
   * @member {Boolean} canManageContent
   */
  exports.prototype.canManageContent = undefined;

  return exports;

}));
