/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/QuestionSource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./QuestionSource'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.Exam = factory(root.KolibriApi.ApiClient, root.KolibriApi.QuestionSource);
  }
}(this, function(ApiClient, QuestionSource) {
  'use strict';

  /**
   * The Exam model module.
   * @module model/Exam
   * @version v0
   */

  /**
   * Constructs a new <code>Exam</code>.
   * @alias module:model/Exam
   * @class
   * @param title {String} 
   * @param questionCount {Number} 
   * @param collection {String} 
   * @param dateArchived {Date} 
   * @param dateActivated {Date} 
   * @param assignments {Array.<String>} 
   * @param creator {String} 
   */
  var exports = function(title, questionCount, collection, dateArchived, dateActivated, assignments, creator) {
    this.title = title;
    this.questionCount = questionCount;
    this.collection = collection;
    this.dateArchived = dateArchived;
    this.dateActivated = dateActivated;
    this.assignments = assignments;
    this.creator = creator;
  };

  /**
   * Constructs a <code>Exam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Exam} obj Optional instance to populate.
   * @return {module:model/Exam} The populated <code>Exam</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('question_count'))
        obj.questionCount = ApiClient.convertToType(data['question_count'], 'Number');
      if (data.hasOwnProperty('question_sources'))
        obj.questionSources = ApiClient.convertToType(data['question_sources'], [QuestionSource]);
      if (data.hasOwnProperty('seed'))
        obj.seed = ApiClient.convertToType(data['seed'], 'Number');
      if (data.hasOwnProperty('active'))
        obj.active = ApiClient.convertToType(data['active'], 'Boolean');
      if (data.hasOwnProperty('collection'))
        obj.collection = ApiClient.convertToType(data['collection'], 'String');
      if (data.hasOwnProperty('archive'))
        obj.archive = ApiClient.convertToType(data['archive'], 'Boolean');
      if (data.hasOwnProperty('date_archived'))
        obj.dateArchived = ApiClient.convertToType(data['date_archived'], 'Date');
      if (data.hasOwnProperty('date_activated'))
        obj.dateActivated = ApiClient.convertToType(data['date_activated'], 'Date');
      if (data.hasOwnProperty('assignments'))
        obj.assignments = ApiClient.convertToType(data['assignments'], ['String']);
      if (data.hasOwnProperty('creator'))
        obj.creator = ApiClient.convertToType(data['creator'], 'String');
      if (data.hasOwnProperty('data_model_version'))
        obj.dataModelVersion = ApiClient.convertToType(data['data_model_version'], 'Number');
      if (data.hasOwnProperty('learners_see_fixed_order'))
        obj.learnersSeeFixedOrder = ApiClient.convertToType(data['learners_see_fixed_order'], 'Boolean');
      if (data.hasOwnProperty('learner_ids'))
        obj.learnerIds = ApiClient.convertToType(data['learner_ids'], ['String']);
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * @member {Number} questionCount
   */
  exports.prototype.questionCount = undefined;

  /**
   * @member {Array.<module:model/QuestionSource>} questionSources
   */
  exports.prototype.questionSources = undefined;

  /**
   * @member {Number} seed
   */
  exports.prototype.seed = undefined;

  /**
   * @member {Boolean} active
   */
  exports.prototype.active = undefined;

  /**
   * @member {String} collection
   */
  exports.prototype.collection = undefined;

  /**
   * @member {Boolean} archive
   */
  exports.prototype.archive = undefined;

  /**
   * @member {Date} dateArchived
   */
  exports.prototype.dateArchived = undefined;

  /**
   * @member {Date} dateActivated
   */
  exports.prototype.dateActivated = undefined;

  /**
   * @member {Array.<String>} assignments
   */
  exports.prototype.assignments = undefined;

  /**
   * @member {String} creator
   */
  exports.prototype.creator = undefined;

  /**
   * @member {Number} dataModelVersion
   */
  exports.prototype.dataModelVersion = undefined;

  /**
   * @member {Boolean} learnersSeeFixedOrder
   */
  exports.prototype.learnersSeeFixedOrder = undefined;

  /**
   * @member {Array.<String>} learnerIds
   */
  exports.prototype.learnerIds = undefined;

  return exports;

}));
