/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Role'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Role'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.FacilityUser = factory(root.KolibriApi.ApiClient, root.KolibriApi.Role);
  }
}(this, function(ApiClient, Role) {
  'use strict';

  /**
   * The FacilityUser model module.
   * @module model/FacilityUser
   * @version v0
   */

  /**
   * Constructs a new <code>FacilityUser</code>.
   * @alias module:model/FacilityUser
   * @class
   * @param username {String} Required. 30 characters or fewer. Letters and digits only
   * @param password {String} 
   * @param facility {String} 
   */
  var exports = function(username, password, facility) {
    this.username = username;
    this.password = password;
    this.facility = facility;
  };

  /**
   * Constructs a <code>FacilityUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FacilityUser} obj Optional instance to populate.
   * @return {module:model/FacilityUser} The populated <code>FacilityUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('full_name'))
        obj.fullName = ApiClient.convertToType(data['full_name'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('facility'))
        obj.facility = ApiClient.convertToType(data['facility'], 'String');
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], [Role]);
      if (data.hasOwnProperty('is_superuser'))
        obj.isSuperuser = ApiClient.convertToType(data['is_superuser'], 'String');
      if (data.hasOwnProperty('id_number'))
        obj.idNumber = ApiClient.convertToType(data['id_number'], 'String');
      if (data.hasOwnProperty('gender'))
        obj.gender = ApiClient.convertToType(data['gender'], 'String');
      if (data.hasOwnProperty('birth_year'))
        obj.birthYear = ApiClient.convertToType(data['birth_year'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * Required. 30 characters or fewer. Letters and digits only
   * @member {String} username
   */
  exports.prototype.username = undefined;

  /**
   * @member {String} fullName
   */
  exports.prototype.fullName = undefined;

  /**
   * @member {String} password
   */
  exports.prototype.password = undefined;

  /**
   * @member {String} facility
   */
  exports.prototype.facility = undefined;

  /**
   * @member {Array.<module:model/Role>} roles
   */
  exports.prototype.roles = undefined;

  /**
   * @member {String} isSuperuser
   */
  exports.prototype.isSuperuser = undefined;

  /**
   * @member {String} idNumber
   */
  exports.prototype.idNumber = undefined;

  /**
   * @member {module:model/FacilityUser.GenderEnum} gender
   */
  exports.prototype.gender = undefined;

  /**
   * @member {String} birthYear
   */
  exports.prototype.birthYear = undefined;


  /**
   * Allowed values for the <code>gender</code> property.
   * @enum {String}
   * @readonly
   */
  exports.GenderEnum = {
    /**
     * value: "MALE"
     * @const
     */
    MALE: "MALE",

    /**
     * value: "FEMALE"
     * @const
     */
    FEMALE: "FEMALE",

    /**
     * value: "NOT_SPECIFIED"
     * @const
     */
    NOT_SPECIFIED: "NOT_SPECIFIED",

    /**
     * value: "DEFERRED"
     * @const
     */
    DEFERRED: "DEFERRED"
  };

  return exports;

}));
