/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.FacilityDataset = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The FacilityDataset model module.
   * @module model/FacilityDataset
   * @version v0
   */

  /**
   * Constructs a new <code>FacilityDataset</code>.
   * @alias module:model/FacilityDataset
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>FacilityDataset</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FacilityDataset} obj Optional instance to populate.
   * @return {module:model/FacilityDataset} The populated <code>FacilityDataset</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('learner_can_edit_username'))
        obj.learnerCanEditUsername = ApiClient.convertToType(data['learner_can_edit_username'], 'Boolean');
      if (data.hasOwnProperty('learner_can_edit_name'))
        obj.learnerCanEditName = ApiClient.convertToType(data['learner_can_edit_name'], 'Boolean');
      if (data.hasOwnProperty('learner_can_edit_password'))
        obj.learnerCanEditPassword = ApiClient.convertToType(data['learner_can_edit_password'], 'Boolean');
      if (data.hasOwnProperty('learner_can_sign_up'))
        obj.learnerCanSignUp = ApiClient.convertToType(data['learner_can_sign_up'], 'Boolean');
      if (data.hasOwnProperty('learner_can_delete_account'))
        obj.learnerCanDeleteAccount = ApiClient.convertToType(data['learner_can_delete_account'], 'Boolean');
      if (data.hasOwnProperty('learner_can_login_with_no_password'))
        obj.learnerCanLoginWithNoPassword = ApiClient.convertToType(data['learner_can_login_with_no_password'], 'Boolean');
      if (data.hasOwnProperty('show_download_button_in_learn'))
        obj.showDownloadButtonInLearn = ApiClient.convertToType(data['show_download_button_in_learn'], 'Boolean');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('registered'))
        obj.registered = ApiClient.convertToType(data['registered'], 'Boolean');
      if (data.hasOwnProperty('preset'))
        obj.preset = ApiClient.convertToType(data['preset'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Boolean} learnerCanEditUsername
   */
  exports.prototype.learnerCanEditUsername = undefined;

  /**
   * @member {Boolean} learnerCanEditName
   */
  exports.prototype.learnerCanEditName = undefined;

  /**
   * @member {Boolean} learnerCanEditPassword
   */
  exports.prototype.learnerCanEditPassword = undefined;

  /**
   * @member {Boolean} learnerCanSignUp
   */
  exports.prototype.learnerCanSignUp = undefined;

  /**
   * @member {Boolean} learnerCanDeleteAccount
   */
  exports.prototype.learnerCanDeleteAccount = undefined;

  /**
   * @member {Boolean} learnerCanLoginWithNoPassword
   */
  exports.prototype.learnerCanLoginWithNoPassword = undefined;

  /**
   * @member {Boolean} showDownloadButtonInLearn
   */
  exports.prototype.showDownloadButtonInLearn = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} location
   */
  exports.prototype.location = undefined;

  /**
   * @member {Boolean} registered
   */
  exports.prototype.registered = undefined;

  /**
   * @member {module:model/FacilityDataset.PresetEnum} preset
   */
  exports.prototype.preset = undefined;


  /**
   * Allowed values for the <code>preset</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PresetEnum = {
    /**
     * value: "formal"
     * @const
     */
    formal: "formal",

    /**
     * value: "nonformal"
     * @const
     */
    nonformal: "nonformal",

    /**
     * value: "informal"
     * @const
     */
    informal: "informal"
  };

  return exports;

}));
