/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Resource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Resource'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.Lesson = factory(root.KolibriApi.ApiClient, root.KolibriApi.Resource);
  }
}(this, function(ApiClient, Resource) {
  'use strict';

  /**
   * The Lesson model module.
   * @module model/Lesson
   * @version v0
   */

  /**
   * Constructs a new <code>Lesson</code>.
   * @alias module:model/Lesson
   * @class
   * @param title {String} 
   * @param collection {String} 
   * @param createdBy {String} 
   */
  var exports = function(title, collection, createdBy) {
    this.title = title;
    this.collection = collection;
    this.createdBy = createdBy;
  };

  /**
   * Constructs a <code>Lesson</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Lesson} obj Optional instance to populate.
   * @return {module:model/Lesson} The populated <code>Lesson</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('resources'))
        obj.resources = ApiClient.convertToType(data['resources'], [Resource]);
      if (data.hasOwnProperty('is_active'))
        obj.isActive = ApiClient.convertToType(data['is_active'], 'Boolean');
      if (data.hasOwnProperty('collection'))
        obj.collection = ApiClient.convertToType(data['collection'], 'String');
      if (data.hasOwnProperty('lesson_assignments'))
        obj.lessonAssignments = ApiClient.convertToType(data['lesson_assignments'], ['String']);
      if (data.hasOwnProperty('learner_ids'))
        obj.learnerIds = ApiClient.convertToType(data['learner_ids'], ['String']);
      if (data.hasOwnProperty('created_by'))
        obj.createdBy = ApiClient.convertToType(data['created_by'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Array.<module:model/Resource>} resources
   */
  exports.prototype.resources = undefined;

  /**
   * @member {Boolean} isActive
   */
  exports.prototype.isActive = undefined;

  /**
   * @member {String} collection
   */
  exports.prototype.collection = undefined;

  /**
   * @member {Array.<String>} lessonAssignments
   */
  exports.prototype.lessonAssignments = undefined;

  /**
   * @member {Array.<String>} learnerIds
   */
  exports.prototype.learnerIds = undefined;

  /**
   * @member {String} createdBy
   */
  exports.prototype.createdBy = undefined;

  return exports;

}));
