/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.MasteryLogViewSet = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The MasteryLogViewSet model module.
   * @module model/MasteryLogViewSet
   * @version v0
   */

  /**
   * Constructs a new <code>MasteryLogViewSet</code>.
   * @alias module:model/MasteryLogViewSet
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>MasteryLogViewSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MasteryLogViewSet} obj Optional instance to populate.
   * @return {module:model/MasteryLogViewSet} The populated <code>MasteryLogViewSet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'String');
      if (data.hasOwnProperty('summarylog'))
        obj.summarylog = ApiClient.convertToType(data['summarylog'], 'String');
      if (data.hasOwnProperty('mastery_criterion'))
        obj.masteryCriterion = ApiClient.convertToType(data['mastery_criterion'], 'String');
      if (data.hasOwnProperty('start_timestamp'))
        obj.startTimestamp = ApiClient.convertToType(data['start_timestamp'], 'String');
      if (data.hasOwnProperty('end_timestamp'))
        obj.endTimestamp = ApiClient.convertToType(data['end_timestamp'], 'String');
      if (data.hasOwnProperty('completion_timestamp'))
        obj.completionTimestamp = ApiClient.convertToType(data['completion_timestamp'], 'String');
      if (data.hasOwnProperty('mastery_level'))
        obj.masteryLevel = ApiClient.convertToType(data['mastery_level'], 'Number');
      if (data.hasOwnProperty('complete'))
        obj.complete = ApiClient.convertToType(data['complete'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {String} user
   */
  exports.prototype.user = undefined;

  /**
   * @member {String} summarylog
   */
  exports.prototype.summarylog = undefined;

  /**
   * @member {String} masteryCriterion
   */
  exports.prototype.masteryCriterion = undefined;

  /**
   * @member {String} startTimestamp
   */
  exports.prototype.startTimestamp = undefined;

  /**
   * @member {String} endTimestamp
   */
  exports.prototype.endTimestamp = undefined;

  /**
   * @member {String} completionTimestamp
   */
  exports.prototype.completionTimestamp = undefined;

  /**
   * @member {Number} masteryLevel
   */
  exports.prototype.masteryLevel = undefined;

  /**
   * @member {Boolean} complete
   */
  exports.prototype.complete = undefined;

  return exports;

}));
