/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.NetworkLocation = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The NetworkLocation model module.
   * @module model/NetworkLocation
   * @version v0
   */

  /**
   * Constructs a new <code>NetworkLocation</code>.
   * @alias module:model/NetworkLocation
   * @class
   * @param baseUrl {String} 
   */
  var exports = function(baseUrl) {
    this.baseUrl = baseUrl;
  };

  /**
   * Constructs a <code>NetworkLocation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NetworkLocation} obj Optional instance to populate.
   * @return {module:model/NetworkLocation} The populated <code>NetworkLocation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('available'))
        obj.available = ApiClient.convertToType(data['available'], 'String');
      if (data.hasOwnProperty('dynamic'))
        obj.dynamic = ApiClient.convertToType(data['dynamic'], 'Boolean');
      if (data.hasOwnProperty('nickname'))
        obj.nickname = ApiClient.convertToType(data['nickname'], 'String');
      if (data.hasOwnProperty('base_url'))
        obj.baseUrl = ApiClient.convertToType(data['base_url'], 'String');
      if (data.hasOwnProperty('device_name'))
        obj.deviceName = ApiClient.convertToType(data['device_name'], 'String');
      if (data.hasOwnProperty('instance_id'))
        obj.instanceId = ApiClient.convertToType(data['instance_id'], 'String');
      if (data.hasOwnProperty('added'))
        obj.added = ApiClient.convertToType(data['added'], 'Date');
      if (data.hasOwnProperty('last_accessed'))
        obj.lastAccessed = ApiClient.convertToType(data['last_accessed'], 'Date');
      if (data.hasOwnProperty('operating_system'))
        obj.operatingSystem = ApiClient.convertToType(data['operating_system'], 'String');
      if (data.hasOwnProperty('application'))
        obj.application = ApiClient.convertToType(data['application'], 'String');
      if (data.hasOwnProperty('kolibri_version'))
        obj.kolibriVersion = ApiClient.convertToType(data['kolibri_version'], 'String');
      if (data.hasOwnProperty('subset_of_users_device'))
        obj.subsetOfUsersDevice = ApiClient.convertToType(data['subset_of_users_device'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} available
   */
  exports.prototype.available = undefined;

  /**
   * @member {Boolean} dynamic
   */
  exports.prototype.dynamic = undefined;

  /**
   * @member {String} nickname
   */
  exports.prototype.nickname = undefined;

  /**
   * @member {String} baseUrl
   */
  exports.prototype.baseUrl = undefined;

  /**
   * @member {String} deviceName
   */
  exports.prototype.deviceName = undefined;

  /**
   * @member {String} instanceId
   */
  exports.prototype.instanceId = undefined;

  /**
   * @member {Date} added
   */
  exports.prototype.added = undefined;

  /**
   * @member {Date} lastAccessed
   */
  exports.prototype.lastAccessed = undefined;

  /**
   * @member {String} operatingSystem
   */
  exports.prototype.operatingSystem = undefined;

  /**
   * @member {String} application
   */
  exports.prototype.application = undefined;

  /**
   * @member {String} kolibriVersion
   */
  exports.prototype.kolibriVersion = undefined;

  /**
   * @member {Boolean} subsetOfUsersDevice
   */
  exports.prototype.subsetOfUsersDevice = undefined;

  return exports;

}));
