/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.NoFacilityFacilityUser = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The NoFacilityFacilityUser model module.
   * @module model/NoFacilityFacilityUser
   * @version v0
   */

  /**
   * Constructs a new <code>NoFacilityFacilityUser</code>.
   * @alias module:model/NoFacilityFacilityUser
   * @class
   * @param username {String} Required. 30 characters or fewer. Letters and digits only
   * @param password {String} 
   */
  var exports = function(username, password) {
    this.username = username;
    this.password = password;
  };

  /**
   * Constructs a <code>NoFacilityFacilityUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NoFacilityFacilityUser} obj Optional instance to populate.
   * @return {module:model/NoFacilityFacilityUser} The populated <code>NoFacilityFacilityUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('full_name'))
        obj.fullName = ApiClient.convertToType(data['full_name'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }

  /**
   * Required. 30 characters or fewer. Letters and digits only
   * @member {String} username
   */
  exports.prototype.username = undefined;

  /**
   * @member {String} fullName
   */
  exports.prototype.fullName = undefined;

  /**
   * @member {String} password
   */
  exports.prototype.password = undefined;

  return exports;

}));
