/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.PublicFacilityUser = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PublicFacilityUser model module.
   * @module model/PublicFacilityUser
   * @version v0
   */

  /**
   * Constructs a new <code>PublicFacilityUser</code>.
   * @alias module:model/PublicFacilityUser
   * @class
   * @param username {String} Required. 30 characters or fewer. Letters and digits only
   * @param facility {String} 
   * @param roles {Array.<String>} 
   */
  var exports = function(username, facility, roles) {
    this.username = username;
    this.facility = facility;
    this.roles = roles;
  };

  /**
   * Constructs a <code>PublicFacilityUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PublicFacilityUser} obj Optional instance to populate.
   * @return {module:model/PublicFacilityUser} The populated <code>PublicFacilityUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('full_name'))
        obj.fullName = ApiClient.convertToType(data['full_name'], 'String');
      if (data.hasOwnProperty('facility'))
        obj.facility = ApiClient.convertToType(data['facility'], 'String');
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], ['String']);
      if (data.hasOwnProperty('is_superuser'))
        obj.isSuperuser = ApiClient.convertToType(data['is_superuser'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * Required. 30 characters or fewer. Letters and digits only
   * @member {String} username
   */
  exports.prototype.username = undefined;

  /**
   * @member {String} fullName
   */
  exports.prototype.fullName = undefined;

  /**
   * @member {String} facility
   */
  exports.prototype.facility = undefined;

  /**
   * @member {Array.<String>} roles
   */
  exports.prototype.roles = undefined;

  /**
   * @member {String} isSuperuser
   */
  exports.prototype.isSuperuser = undefined;

  return exports;

}));
