/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.RecordMaxCounterBuffer = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RecordMaxCounterBuffer model module.
   * @module model/RecordMaxCounterBuffer
   * @version v0
   */

  /**
   * Constructs a new <code>RecordMaxCounterBuffer</code>.
   * @alias module:model/RecordMaxCounterBuffer
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RecordMaxCounterBuffer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordMaxCounterBuffer} obj Optional instance to populate.
   * @return {module:model/RecordMaxCounterBuffer} The populated <code>RecordMaxCounterBuffer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('transfer_session'))
        obj.transferSession = ApiClient.convertToType(data['transfer_session'], 'String');
      if (data.hasOwnProperty('model_uuid'))
        obj.modelUuid = ApiClient.convertToType(data['model_uuid'], 'String');
      if (data.hasOwnProperty('instance_id'))
        obj.instanceId = ApiClient.convertToType(data['instance_id'], 'String');
      if (data.hasOwnProperty('counter'))
        obj.counter = ApiClient.convertToType(data['counter'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} transferSession
   */
  exports.prototype.transferSession = undefined;

  /**
   * @member {String} modelUuid
   */
  exports.prototype.modelUuid = undefined;

  /**
   * @member {String} instanceId
   */
  exports.prototype.instanceId = undefined;

  /**
   * @member {Number} counter
   */
  exports.prototype.counter = undefined;

  return exports;

}));
