/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.SharedKey = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SharedKey model module.
   * @module model/SharedKey
   * @version v0
   */

  /**
   * Constructs a new <code>SharedKey</code>.
   * @alias module:model/SharedKey
   * @class
   * @param publicKey {String} 
   */
  var exports = function(publicKey) {
    this.publicKey = publicKey;
  };

  /**
   * Constructs a <code>SharedKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SharedKey} obj Optional instance to populate.
   * @return {module:model/SharedKey} The populated <code>SharedKey</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('public_key'))
        obj.publicKey = ApiClient.convertToType(data['public_key'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} publicKey
   */
  exports.prototype.publicKey = undefined;

  return exports;

}));
