/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.UserSyncStatusViewSet = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UserSyncStatusViewSet model module.
   * @module model/UserSyncStatusViewSet
   * @version v0
   */

  /**
   * Constructs a new <code>UserSyncStatusViewSet</code>.
   * @alias module:model/UserSyncStatusViewSet
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UserSyncStatusViewSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserSyncStatusViewSet} obj Optional instance to populate.
   * @return {module:model/UserSyncStatusViewSet} The populated <code>UserSyncStatusViewSet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('queued'))
        obj.queued = ApiClient.convertToType(data['queued'], 'Boolean');
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'String');
    }
    return obj;
  }

  /**
   * @member {Boolean} queued
   */
  exports.prototype.queued = undefined;

  /**
   * @member {String} user
   */
  exports.prototype.user = undefined;

  return exports;

}));
