/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KolibriApi) {
      root.KolibriApi = {};
    }
    root.KolibriApi.UserContentNodeViewset = factory(root.KolibriApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UserContentNodeViewset model module.
   * @module model/UserContentNodeViewset
   * @version v0
   */

  /**
   * Constructs a new <code>UserContentNodeViewset</code>.
   * @alias module:model/UserContentNodeViewset
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UserContentNodeViewset</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserContentNodeViewset} obj Optional instance to populate.
   * @return {module:model/UserContentNodeViewset} The populated <code>UserContentNodeViewset</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('author'))
        obj.author = ApiClient.convertToType(data['author'], 'String');
      if (data.hasOwnProperty('available'))
        obj.available = ApiClient.convertToType(data['available'], 'Boolean');
      if (data.hasOwnProperty('channel_id'))
        obj.channelId = ApiClient.convertToType(data['channel_id'], 'String');
      if (data.hasOwnProperty('coach_content'))
        obj.coachContent = ApiClient.convertToType(data['coach_content'], 'Boolean');
      if (data.hasOwnProperty('content_id'))
        obj.contentId = ApiClient.convertToType(data['content_id'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('kind'))
        obj.kind = ApiClient.convertToType(data['kind'], 'String');
      if (data.hasOwnProperty('lang_id'))
        obj.langId = ApiClient.convertToType(data['lang_id'], 'String');
      if (data.hasOwnProperty('license_description'))
        obj.licenseDescription = ApiClient.convertToType(data['license_description'], 'String');
      if (data.hasOwnProperty('license_name'))
        obj.licenseName = ApiClient.convertToType(data['license_name'], 'String');
      if (data.hasOwnProperty('license_owner'))
        obj.licenseOwner = ApiClient.convertToType(data['license_owner'], 'String');
      if (data.hasOwnProperty('num_coach_contents'))
        obj.numCoachContents = ApiClient.convertToType(data['num_coach_contents'], 'Number');
      if (data.hasOwnProperty('options'))
        obj.options = ApiClient.convertToType(data['options'], 'String');
      if (data.hasOwnProperty('parent'))
        obj.parent = ApiClient.convertToType(data['parent'], 'String');
      if (data.hasOwnProperty('sort_order'))
        obj.sortOrder = ApiClient.convertToType(data['sort_order'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('lft'))
        obj.lft = ApiClient.convertToType(data['lft'], 'Number');
      if (data.hasOwnProperty('rght'))
        obj.rght = ApiClient.convertToType(data['rght'], 'Number');
      if (data.hasOwnProperty('tree_id'))
        obj.treeId = ApiClient.convertToType(data['tree_id'], 'Number');
      if (data.hasOwnProperty('learning_activities'))
        obj.learningActivities = ApiClient.convertToType(data['learning_activities'], 'String');
      if (data.hasOwnProperty('grade_levels'))
        obj.gradeLevels = ApiClient.convertToType(data['grade_levels'], 'String');
      if (data.hasOwnProperty('resource_types'))
        obj.resourceTypes = ApiClient.convertToType(data['resource_types'], 'String');
      if (data.hasOwnProperty('accessibility_labels'))
        obj.accessibilityLabels = ApiClient.convertToType(data['accessibility_labels'], 'String');
      if (data.hasOwnProperty('categories'))
        obj.categories = ApiClient.convertToType(data['categories'], 'String');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('ancestors'))
        obj.ancestors = ApiClient.convertToType(data['ancestors'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} author
   */
  exports.prototype.author = undefined;

  /**
   * @member {Boolean} available
   */
  exports.prototype.available = undefined;

  /**
   * @member {String} channelId
   */
  exports.prototype.channelId = undefined;

  /**
   * @member {Boolean} coachContent
   */
  exports.prototype.coachContent = undefined;

  /**
   * @member {String} contentId
   */
  exports.prototype.contentId = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {module:model/UserContentNodeViewset.KindEnum} kind
   */
  exports.prototype.kind = undefined;

  /**
   * @member {String} langId
   */
  exports.prototype.langId = undefined;

  /**
   * @member {String} licenseDescription
   */
  exports.prototype.licenseDescription = undefined;

  /**
   * @member {String} licenseName
   */
  exports.prototype.licenseName = undefined;

  /**
   * @member {String} licenseOwner
   */
  exports.prototype.licenseOwner = undefined;

  /**
   * @member {Number} numCoachContents
   */
  exports.prototype.numCoachContents = undefined;

  /**
   * @member {String} options
   */
  exports.prototype.options = undefined;

  /**
   * @member {String} parent
   */
  exports.prototype.parent = undefined;

  /**
   * @member {Number} sortOrder
   */
  exports.prototype.sortOrder = undefined;

  /**
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * @member {Number} lft
   */
  exports.prototype.lft = undefined;

  /**
   * @member {Number} rght
   */
  exports.prototype.rght = undefined;

  /**
   * @member {Number} treeId
   */
  exports.prototype.treeId = undefined;

  /**
   * @member {String} learningActivities
   */
  exports.prototype.learningActivities = undefined;

  /**
   * @member {String} gradeLevels
   */
  exports.prototype.gradeLevels = undefined;

  /**
   * @member {String} resourceTypes
   */
  exports.prototype.resourceTypes = undefined;

  /**
   * @member {String} accessibilityLabels
   */
  exports.prototype.accessibilityLabels = undefined;

  /**
   * @member {String} categories
   */
  exports.prototype.categories = undefined;

  /**
   * @member {Number} duration
   */
  exports.prototype.duration = undefined;

  /**
   * @member {String} ancestors
   */
  exports.prototype.ancestors = undefined;


  /**
   * Allowed values for the <code>kind</code> property.
   * @enum {String}
   * @readonly
   */
  exports.KindEnum = {
    /**
     * value: "topic"
     * @const
     */
    topic: "topic",

    /**
     * value: "video"
     * @const
     */
    video: "video",

    /**
     * value: "audio"
     * @const
     */
    audio: "audio",

    /**
     * value: "exercise"
     * @const
     */
    exercise: "exercise",

    /**
     * value: "document"
     * @const
     */
    document: "document",

    /**
     * value: "html5"
     * @const
     */
    html5: "html5",

    /**
     * value: "slideshow"
     * @const
     */
    slideshow: "slideshow",

    /**
     * value: "h5p"
     * @const
     */
    h5p: "h5p",

    /**
     * value: "zim"
     * @const
     */
    zim: "zim",

    /**
     * value: "quiz"
     * @const
     */
    quiz: "quiz"
  };

  return exports;

}));
