/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolibriApi);
  }
}(this, function(expect, KolibriApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Certificate', function() {
      beforeEach(function() {
        instance = new KolibriApi.Certificate();
      });

      it('should create an instance of Certificate', function() {
        // TODO: update the code to test Certificate
        expect(instance).to.be.a(KolibriApi.Certificate);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property parent (base name: "parent")', function() {
        // TODO: update the code to test the property parent
        expect(instance).to.have.property('parent');
        // expect(instance.parent).to.be(expectedValueLiteral);
      });

      it('should have the property profile (base name: "profile")', function() {
        // TODO: update the code to test the property profile
        expect(instance).to.have.property('profile');
        // expect(instance.profile).to.be(expectedValueLiteral);
      });

      it('should have the property scopeDefinition (base name: "scope_definition")', function() {
        // TODO: update the code to test the property scopeDefinition
        expect(instance).to.have.property('scopeDefinition');
        // expect(instance.scopeDefinition).to.be(expectedValueLiteral);
      });

      it('should have the property scopeVersion (base name: "scope_version")', function() {
        // TODO: update the code to test the property scopeVersion
        expect(instance).to.have.property('scopeVersion');
        // expect(instance.scopeVersion).to.be(expectedValueLiteral);
      });

      it('should have the property scopeParams (base name: "scope_params")', function() {
        // TODO: update the code to test the property scopeParams
        expect(instance).to.have.property('scopeParams');
        // expect(instance.scopeParams).to.be(expectedValueLiteral);
      });

      it('should have the property publicKey (base name: "public_key")', function() {
        // TODO: update the code to test the property publicKey
        expect(instance).to.have.property('publicKey');
        // expect(instance.publicKey).to.be(expectedValueLiteral);
      });

      it('should have the property serialized (base name: "serialized")', function() {
        // TODO: update the code to test the property serialized
        expect(instance).to.have.property('serialized');
        // expect(instance.serialized).to.be(expectedValueLiteral);
      });

      it('should have the property signature (base name: "signature")', function() {
        // TODO: update the code to test the property signature
        expect(instance).to.have.property('signature');
        // expect(instance.signature).to.be(expectedValueLiteral);
      });

      it('should have the property salt (base name: "salt")', function() {
        // TODO: update the code to test the property salt
        expect(instance).to.have.property('salt');
        // expect(instance.salt).to.be(expectedValueLiteral);
      });

    });
  });

}));
