/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolibriApi);
  }
}(this, function(expect, KolibriApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Language', function() {
      beforeEach(function() {
        instance = new KolibriApi.Language();
      });

      it('should create an instance of Language', function() {
        // TODO: update the code to test Language
        expect(instance).to.be.a(KolibriApi.Language);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property langCode (base name: "lang_code")', function() {
        // TODO: update the code to test the property langCode
        expect(instance).to.have.property('langCode');
        // expect(instance.langCode).to.be(expectedValueLiteral);
      });

      it('should have the property langSubcode (base name: "lang_subcode")', function() {
        // TODO: update the code to test the property langSubcode
        expect(instance).to.have.property('langSubcode');
        // expect(instance.langSubcode).to.be(expectedValueLiteral);
      });

      it('should have the property langName (base name: "lang_name")', function() {
        // TODO: update the code to test the property langName
        expect(instance).to.have.property('langName');
        // expect(instance.langName).to.be(expectedValueLiteral);
      });

      it('should have the property langDirection (base name: "lang_direction")', function() {
        // TODO: update the code to test the property langDirection
        expect(instance).to.have.property('langDirection');
        // expect(instance.langDirection).to.be(expectedValueLiteral);
      });

    });
  });

}));
