/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolibriApi);
  }
}(this, function(expect, KolibriApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LessonReport', function() {
      beforeEach(function() {
        instance = new KolibriApi.LessonReport();
      });

      it('should create an instance of LessonReport', function() {
        // TODO: update the code to test LessonReport
        expect(instance).to.be.a(KolibriApi.LessonReport);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property progress (base name: "progress")', function() {
        // TODO: update the code to test the property progress
        expect(instance).to.have.property('progress');
        // expect(instance.progress).to.be(expectedValueLiteral);
      });

      it('should have the property totalLearners (base name: "total_learners")', function() {
        // TODO: update the code to test the property totalLearners
        expect(instance).to.have.property('totalLearners');
        // expect(instance.totalLearners).to.be(expectedValueLiteral);
      });

    });
  });

}));
