/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolibriApi);
  }
}(this, function(expect, KolibriApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MasteryLogViewSet', function() {
      beforeEach(function() {
        instance = new KolibriApi.MasteryLogViewSet();
      });

      it('should create an instance of MasteryLogViewSet', function() {
        // TODO: update the code to test MasteryLogViewSet
        expect(instance).to.be.a(KolibriApi.MasteryLogViewSet);
      });

      it('should have the property user (base name: "user")', function() {
        // TODO: update the code to test the property user
        expect(instance).to.have.property('user');
        // expect(instance.user).to.be(expectedValueLiteral);
      });

      it('should have the property summarylog (base name: "summarylog")', function() {
        // TODO: update the code to test the property summarylog
        expect(instance).to.have.property('summarylog');
        // expect(instance.summarylog).to.be(expectedValueLiteral);
      });

      it('should have the property masteryCriterion (base name: "mastery_criterion")', function() {
        // TODO: update the code to test the property masteryCriterion
        expect(instance).to.have.property('masteryCriterion');
        // expect(instance.masteryCriterion).to.be(expectedValueLiteral);
      });

      it('should have the property startTimestamp (base name: "start_timestamp")', function() {
        // TODO: update the code to test the property startTimestamp
        expect(instance).to.have.property('startTimestamp');
        // expect(instance.startTimestamp).to.be(expectedValueLiteral);
      });

      it('should have the property endTimestamp (base name: "end_timestamp")', function() {
        // TODO: update the code to test the property endTimestamp
        expect(instance).to.have.property('endTimestamp');
        // expect(instance.endTimestamp).to.be(expectedValueLiteral);
      });

      it('should have the property completionTimestamp (base name: "completion_timestamp")', function() {
        // TODO: update the code to test the property completionTimestamp
        expect(instance).to.have.property('completionTimestamp');
        // expect(instance.completionTimestamp).to.be(expectedValueLiteral);
      });

      it('should have the property masteryLevel (base name: "mastery_level")', function() {
        // TODO: update the code to test the property masteryLevel
        expect(instance).to.have.property('masteryLevel');
        // expect(instance.masteryLevel).to.be(expectedValueLiteral);
      });

      it('should have the property complete (base name: "complete")', function() {
        // TODO: update the code to test the property complete
        expect(instance).to.have.property('complete');
        // expect(instance.complete).to.be(expectedValueLiteral);
      });

    });
  });

}));
