/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolibriApi);
  }
}(this, function(expect, KolibriApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Resource', function() {
      beforeEach(function() {
        instance = new KolibriApi.Resource();
      });

      it('should create an instance of Resource', function() {
        // TODO: update the code to test Resource
        expect(instance).to.be.a(KolibriApi.Resource);
      });

      it('should have the property contentId (base name: "content_id")', function() {
        // TODO: update the code to test the property contentId
        expect(instance).to.have.property('contentId');
        // expect(instance.contentId).to.be(expectedValueLiteral);
      });

      it('should have the property channelId (base name: "channel_id")', function() {
        // TODO: update the code to test the property channelId
        expect(instance).to.have.property('channelId');
        // expect(instance.channelId).to.be(expectedValueLiteral);
      });

      it('should have the property contentnodeId (base name: "contentnode_id")', function() {
        // TODO: update the code to test the property contentnodeId
        expect(instance).to.have.property('contentnodeId');
        // expect(instance.contentnodeId).to.be(expectedValueLiteral);
      });

    });
  });

}));
