/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolibriApi);
  }
}(this, function(expect, KolibriApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolibriApi.LearnApi();
  });

  describe('(package)', function() {
    describe('LearnApi', function() {
      describe('learnApiHomehydrateList', function() {
        it('should call learnApiHomehydrateList successfully', function(done) {
          // TODO: uncomment learnApiHomehydrateList call
          /*

          instance.learnApiHomehydrateList(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('learnApiLearnerclassroomList', function() {
        it('should call learnApiLearnerclassroomList successfully', function(done) {
          // TODO: uncomment learnApiLearnerclassroomList call and complete the assertions
          /*

          instance.learnApiLearnerclassroomList(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Object);
              // expect(data).to.be(null);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('learnApiLearnerclassroomRead', function() {
        it('should call learnApiLearnerclassroomRead successfully', function(done) {
          // TODO: uncomment, update parameter values for learnApiLearnerclassroomRead call and complete the assertions
          /*
          var id = "id_example";

          instance.learnApiLearnerclassroomRead(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('learnApiLearnerlessonList', function() {
        it('should call learnApiLearnerlessonList successfully', function(done) {
          // TODO: uncomment learnApiLearnerlessonList call and complete the assertions
          /*

          instance.learnApiLearnerlessonList(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Object);
              // expect(data).to.be(null);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('learnApiLearnerlessonRead', function() {
        it('should call learnApiLearnerlessonRead successfully', function(done) {
          // TODO: uncomment, update parameter values for learnApiLearnerlessonRead call and complete the assertions
          /*
          var id = "id_example";

          instance.learnApiLearnerlessonRead(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('learnApiStateList', function() {
        it('should call learnApiStateList successfully', function(done) {
          // TODO: uncomment learnApiStateList call
          /*

          instance.learnApiStateList(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
