/*
 * Kolibri API
 * Kolibri Swagger API
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolibriApi);
  }
}(this, function(expect, KolibriApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolibriApi.SetupApi();
  });

  describe('(package)', function() {
    describe('SetupApi', function() {
      describe('setupApiFacilityimportCreatesuperuser', function() {
        it('should call setupApiFacilityimportCreatesuperuser successfully', function(done) {
          // TODO: uncomment setupApiFacilityimportCreatesuperuser call
          /*

          instance.setupApiFacilityimportCreatesuperuser(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiFacilityimportFacilityadmins', function() {
        it('should call setupApiFacilityimportFacilityadmins successfully', function(done) {
          // TODO: uncomment setupApiFacilityimportFacilityadmins call
          /*

          instance.setupApiFacilityimportFacilityadmins(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiFacilityimportGrantsuperuserpermissions', function() {
        it('should call setupApiFacilityimportGrantsuperuserpermissions successfully', function(done) {
          // TODO: uncomment setupApiFacilityimportGrantsuperuserpermissions call
          /*

          instance.setupApiFacilityimportGrantsuperuserpermissions(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiFacilityimportListfacilitylearners', function() {
        it('should call setupApiFacilityimportListfacilitylearners successfully', function(done) {
          // TODO: uncomment setupApiFacilityimportListfacilitylearners call
          /*

          instance.setupApiFacilityimportListfacilitylearners(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiFacilityimportProvisiondevice', function() {
        it('should call setupApiFacilityimportProvisiondevice successfully', function(done) {
          // TODO: uncomment setupApiFacilityimportProvisiondevice call
          /*

          instance.setupApiFacilityimportProvisiondevice(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiRestartzeroconfRestart', function() {
        it('should call setupApiRestartzeroconfRestart successfully', function(done) {
          // TODO: uncomment setupApiRestartzeroconfRestart call
          /*

          instance.setupApiRestartzeroconfRestart(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksCanceltask', function() {
        it('should call setupApiSoudtasksCanceltask successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksCanceltask call
          /*

          instance.setupApiSoudtasksCanceltask(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksChanneldiffstats', function() {
        it('should call setupApiSoudtasksChanneldiffstats successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksChanneldiffstats call
          /*

          instance.setupApiSoudtasksChanneldiffstats(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksCleartask', function() {
        it('should call setupApiSoudtasksCleartask successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksCleartask call
          /*

          instance.setupApiSoudtasksCleartask(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksCleartasks', function() {
        it('should call setupApiSoudtasksCleartasks successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksCleartasks call
          /*

          instance.setupApiSoudtasksCleartasks(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksCreate', function() {
        it('should call setupApiSoudtasksCreate successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksCreate call
          /*

          instance.setupApiSoudtasksCreate(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksDelete', function() {
        it('should call setupApiSoudtasksDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for setupApiSoudtasksDelete call
          /*
          var id = "id_example";

          instance.setupApiSoudtasksDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksDeletefinishedtasks', function() {
        it('should call setupApiSoudtasksDeletefinishedtasks successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksDeletefinishedtasks call
          /*

          instance.setupApiSoudtasksDeletefinishedtasks(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksExportuserstocsv', function() {
        it('should call setupApiSoudtasksExportuserstocsv successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksExportuserstocsv call
          /*

          instance.setupApiSoudtasksExportuserstocsv(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksImportusersfromcsv', function() {
        it('should call setupApiSoudtasksImportusersfromcsv successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksImportusersfromcsv call
          /*

          instance.setupApiSoudtasksImportusersfromcsv(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksList', function() {
        it('should call setupApiSoudtasksList successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksList call
          /*

          instance.setupApiSoudtasksList(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksLocaldrive', function() {
        it('should call setupApiSoudtasksLocaldrive successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksLocaldrive call
          /*

          instance.setupApiSoudtasksLocaldrive(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksRead', function() {
        it('should call setupApiSoudtasksRead successfully', function(done) {
          // TODO: uncomment, update parameter values for setupApiSoudtasksRead call
          /*
          var id = "id_example";

          instance.setupApiSoudtasksRead(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksRestarttask', function() {
        it('should call setupApiSoudtasksRestarttask successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksRestarttask call
          /*

          instance.setupApiSoudtasksRestarttask(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartbulkdelete', function() {
        it('should call setupApiSoudtasksStartbulkdelete successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartbulkdelete call
          /*

          instance.setupApiSoudtasksStartbulkdelete(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartchannelupdate', function() {
        it('should call setupApiSoudtasksStartchannelupdate successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartchannelupdate call
          /*

          instance.setupApiSoudtasksStartchannelupdate(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartdeletechannel', function() {
        it('should call setupApiSoudtasksStartdeletechannel successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartdeletechannel call
          /*

          instance.setupApiSoudtasksStartdeletechannel(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartdiskbulkexport', function() {
        it('should call setupApiSoudtasksStartdiskbulkexport successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartdiskbulkexport call
          /*

          instance.setupApiSoudtasksStartdiskbulkexport(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartdiskbulkimport', function() {
        it('should call setupApiSoudtasksStartdiskbulkimport successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartdiskbulkimport call
          /*

          instance.setupApiSoudtasksStartdiskbulkimport(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartdiskchannelimport', function() {
        it('should call setupApiSoudtasksStartdiskchannelimport successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartdiskchannelimport call
          /*

          instance.setupApiSoudtasksStartdiskchannelimport(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartdiskcontentimport', function() {
        it('should call setupApiSoudtasksStartdiskcontentimport successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartdiskcontentimport call
          /*

          instance.setupApiSoudtasksStartdiskcontentimport(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartdiskexport', function() {
        it('should call setupApiSoudtasksStartdiskexport successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartdiskexport call
          /*

          instance.setupApiSoudtasksStartdiskexport(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartexportlogcsv', function() {
        it('should call setupApiSoudtasksStartexportlogcsv successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartexportlogcsv call
          /*

          instance.setupApiSoudtasksStartexportlogcsv(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartremotebulkimport', function() {
        it('should call setupApiSoudtasksStartremotebulkimport successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartremotebulkimport call
          /*

          instance.setupApiSoudtasksStartremotebulkimport(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartremotechannelimport', function() {
        it('should call setupApiSoudtasksStartremotechannelimport successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartremotechannelimport call
          /*

          instance.setupApiSoudtasksStartremotechannelimport(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiSoudtasksStartremotecontentimport', function() {
        it('should call setupApiSoudtasksStartremotecontentimport successfully', function(done) {
          // TODO: uncomment setupApiSoudtasksStartremotecontentimport call
          /*

          instance.setupApiSoudtasksStartremotecontentimport(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksCanceltask', function() {
        it('should call setupApiTasksCanceltask successfully', function(done) {
          // TODO: uncomment setupApiTasksCanceltask call
          /*

          instance.setupApiTasksCanceltask(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksCleartask', function() {
        it('should call setupApiTasksCleartask successfully', function(done) {
          // TODO: uncomment setupApiTasksCleartask call
          /*

          instance.setupApiTasksCleartask(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksCleartasks', function() {
        it('should call setupApiTasksCleartasks successfully', function(done) {
          // TODO: uncomment setupApiTasksCleartasks call
          /*

          instance.setupApiTasksCleartasks(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksCreate', function() {
        it('should call setupApiTasksCreate successfully', function(done) {
          // TODO: uncomment setupApiTasksCreate call
          /*

          instance.setupApiTasksCreate(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksDelete', function() {
        it('should call setupApiTasksDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for setupApiTasksDelete call
          /*
          var id = "id_example";

          instance.setupApiTasksDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksDeletefinishedtasks', function() {
        it('should call setupApiTasksDeletefinishedtasks successfully', function(done) {
          // TODO: uncomment setupApiTasksDeletefinishedtasks call
          /*

          instance.setupApiTasksDeletefinishedtasks(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksList', function() {
        it('should call setupApiTasksList successfully', function(done) {
          // TODO: uncomment setupApiTasksList call
          /*

          instance.setupApiTasksList(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksRead', function() {
        it('should call setupApiTasksRead successfully', function(done) {
          // TODO: uncomment, update parameter values for setupApiTasksRead call
          /*
          var id = "id_example";

          instance.setupApiTasksRead(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksRestarttask', function() {
        it('should call setupApiTasksRestarttask successfully', function(done) {
          // TODO: uncomment setupApiTasksRestarttask call
          /*

          instance.setupApiTasksRestarttask(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setupApiTasksStartpeerfacilityimport', function() {
        it('should call setupApiTasksStartpeerfacilityimport successfully', function(done) {
          // TODO: uncomment setupApiTasksStartpeerfacilityimport call
          /*

          instance.setupApiTasksStartpeerfacilityimport(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
